In [ ]:
print("Hello")

Hello


In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.zeros((2,2)) ### zeroes
print("zeroes:", arr)

arr = np.ones((2,3))  ### ones
print("ones:", arr)


zeroes: [[0. 0.]
 [0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
arr = np.array([1,2,3,4,5])
print("addition :" ,arr+5) ### scalar addition
print("substraction :", arr-2) ### scalar substraction
print("multiplication :", arr*3) ### scalar multiplication
print("division :", arr/2) ### scalar division
print("exponentiation :", arr**2) ### scalar exponentiation

addition : [ 6  7  8  9 10]
substraction : [-1  0  1  2  3]
multiplication : [ 3  6  9 12 15]
division : [0.5 1.  1.5 2.  2.5]
exponentiation : [ 1  4  9 16 25]


In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print("Element wise addition : " , arr1+arr2)

Element wise addition :  [ 7  9 11 13 15]


In [ ]:
arr = np.array([8,7,55,43,29,95,11])   ### indexing
print("first element: ",arr[0])
print("Element at 1&2 index : ",arr[1:3])


arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]]) ### 2D array 
print("First two rows :" , arr1[0:2])

first element:  8
Element at 1&2 index :  [ 7 55]
First two rows : [[1 2 3]
 [4 5 6]]


In [ ]:
first_arr = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
second_arr = np.array([10,11,12])
print("Broadcasting in numpy : ", first_arr + second_arr)

Broadcasting in numpy :  [[11 13 15]
 [14 16 18]
 [17 19 21]]


In [1]:
# Create a 5x5 array and extract the middle 3x3 block
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]])
print('3 and 3 array: ', arr[3:4, 3:4])


### Try broadcasting : add[1,2,3,4,5] to 4*4 array

arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr3 = np.array([1,2,3,4])  # Changed to length 4 for broadcasting
result = arr2 + arr3
print("Result after broadcasting : ", result)

NameError: name 'np' is not defined